[[redirects]]
    from = "/decks"
    to = "https://archidekt.com/api/decks/cards/?owner=HyperWalrus"
    status = 200
    force = true
    headers = {X-From = "Netlify"}
[[headers]]
    for = "/*"
    [headers.values]
        Access-Control-Allow-Origin = "*"